volumes:
  postgres-data:
    
services:
  postgres:
    image: postgres:17.4
    container_name: pgdb
    environment:
      - TZ=Europe/Amsterdam
      - POSTGRES_PASSWORD
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  ansible:
    image: ansible-postgres-setup
    container_name: ansible
    build:
      context: ansible/docker
    environment:
      - POSTGRES_PASSWORD
      - APP_DB_USER
      - APP_DB_PASSWORD
    volumes:
      - ./ansible:/ansible
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      ansible-playbook
      -i inventory/hosts.yml
      -e "pg_host=postgres"
      -e "pg_admin_password=${POSTGRES_PASSWORD}"
      -e "app_db_user=${APP_DB_USER}"
      -e "app_db_password=${APP_DB_PASSWORD}"
      playbooks/database_setup.yml
