volumes:
  postgres-data:
    
services:
  postgres:
    image: postgres:17.4
    container_name: pgdb
    environment:
      - TZ=Europe/Amsterdam
      - POSTGRES_PASSWORD
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
