networks:
  frontend:
  backend:

volumes:
  postgres-data:
    
services:
  postgres:
    image: postgres:17.4
    container_name: postgres
    environment:
      - TZ=Europe/Amsterdam
      - POSTGRES_PASSWORD
    networks:
      - backend
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  transaction-verifier:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend
      - frontend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
