volumes:
  postgres-data:
    
services:
  postgres:
    image: postgres:17.4
    container_name: pgdb
    environment:
      - TZ=Europe/Amsterdam
      - POSTGRES_PASSWORD
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  ansible:
    image: ansible-postgres-setup
    container_name: ansible
    build:
      context: ansible/docker
    volumes:
      - ./ansible:/ansible
    command: >
      ansible-playbook
      -i /ansible/playbooks/inventory/hosts.yml
      -e "pg_host=postgres"
      /ansible/playbooks/database_setup.yml