---
# PostgreSQL server inventory for Docker Compose setup
postgres_servers:
  hosts:
    postgres:  # This matches the service name in docker-compose.yml
      ansible_connection: local
      ansible_python_interpreter: /usr/local/bin/python3.9
  vars:
    # PostgreSQL connection details
    pg_host: postgres  # Service name from docker-compose
    pg_port: 5432
    pg_admin_user: postgres  # Default superuser in PostgreSQL container
    pg_admin_password: postgres_password  # From POSTGRES_PASSWORD in docker-compose.yml

    app_db_user: app_db_user
    app_db_password: app_db_password

    # New database details
    pg_db_name: transactions

    # Database configuration
    pg_encoding: UTF8
    pg_locale: en_US.UTF-8

