---
# PostgreSQL server inventory
postgres_servers:
  hosts:
    localhost:
      ansible_connection: local

  vars:
    # PostgreSQL connection details
    pg_host: 192.168.2.17
    pg_port: 5432

    # New database details
    pg_db_name: application_db
    pg_db_user: app_user
    pg_db_password: app_password

    # Database configuration
    pg_encoding: UTF8
    pg_locale: en_US.UTF-8