---
- name: PostgreSQL Database Setup
  hosts: postgres_servers
  gather_facts: false


  tasks:

    - name: Create directory for SQL scripts
      file:
        path: /tmp/postgres_setup
        state: directory
        mode: '0755'

    - name: Copy database initialization script
      template:
        src: /ansible/templates/init_db.sql.j2
        dest: /tmp/postgres_setup/init_db.sql
        mode: '0644'

    - name: Copy database tables script
      template:
        src: /ansible/templates/init_db_tables.sql.j2
        dest: //tmp/postgres_setup/tables.sql
        mode: '0644'

    - name: Execute database initialization script
      become_user: "{{ pg_admin_user }}"
      environment:
        PGPASSWORD: "{{ pg_admin_password }}"
      shell: >
        psql
        -h {{ pg_host }}
        -p {{ pg_port }}
        -U {{ pg_admin_user }}
        -f /tmp/postgres_setup/init_db.sql
      register: init_result
      changed_when: "'CREATE USER' in init_result.stdout or 'CREATE DATABASE' in init_result.stdout"

    - name: Display database initialization result
      debug:
        var: init_result.stdout_lines

    - name: Verify database connection
      environment:
        PGPASSWORD: "{{ app_db_password }}"
      shell: >
        psql
        -h {{ pg_host }}
        -p {{ pg_port }}
        -U {{ app_db_user }}
        -d {{ pg_db_name }}
        -c "\conninfo"
      register: connection_test
      ignore_errors: true

    - name: Display connection info
      debug:
        var: connection_test.stdout_lines
      when: connection_test is success

    - name: Execute database tables script
      become_user: "{{ app_db_user }}"
      environment:
        PGPASSWORD: "{{ app_db_password }}"
      shell: >
        psql
        -h {{ pg_host }}
        -p {{ pg_port }}
        -U {{ app_db_user }}
        -d {{ pg_db_name }}
        -f /tmp/postgres_setup/tables.sql
      register: table_result
      changed_when: "'CREATE TABLE' in table_result.stdout"

    - name: Display database tables result
      debug:
        var: table_result.stdout_lines
      when: table_result is success
